### ISSUE TITLE
https-proxy-agent dependency error on fresh install

### ISSUE THREAD

**Issue by mksondej** [locize/locize-cli#89]
## 💥 Regression Report

It seems that the dependency bump in 7.4.12 broke something related to https-proxy-agent.
After the fresh install of the CLI (see steps to reproduce below) a `sync` results in:

```
node:internal/modules/cjs/loader:446
      throw err;
      ^

Error: Cannot find module 'C:\Users\***\AppData\Roaming\npm\node_modules\locize-cli\node_modules\https-proxy-agent\dist\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:438:19)
    at Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (*****\node_modules\locize-cli\request.js:3:25)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  path: '****\\locize-cli\\node_modules\\https-proxy-agent\\package.json',
  requestPath: 'https-proxy-agent'
}

Node.js v18.16.1
```

Downgrading to 7.4.11 fixes the issue.

## Last working version

Worked up to version: 7.14.11

Stopped working in version: 7.14.12

## To Reproduce

```js
npm install -g locize-cli
locize sync --api-key XXXX --project-id YYY
```

## Expected behavior

Expected a successful sync.

## Your Environment

- *runtime version*: node v18.16.1
- *module version*: 7.14.12
- *os*: Windows
- tested both global install, local project install and npx without installing

**Comment by adrai** [comment]
Was not able to reproduce it, but we downgraded that dependency anyway.
v7.14.13 should be ok
